export type ForumItem = {
  id: string;
  title: string;
  description: string;
  href: string;
  icon: string;
  viewers: number;
  topicsCount: string;
  postsCount: string;
  isNew: boolean;
  category: "programming" | "freelancing" | "ai" | "career" | "library" | "community";
  tags: string[];
  latest: {
    title: string;
    type: "سؤال" | "مقال" | "نقاش" | "فرصة";
    authorName: string;
    authorHandle: string;
    avatarUrl?: string;
    relativeTime: string;
    exactTime: string;
  };
};

export type ForumGroup = {
  id: string;
  title: string;
  description: string;
  forums: ForumItem[];
};

export type DiscussionItem = {
  id: string;
  title: string;
  excerpt: string;
  href: string;
  category: string;
  status: "تم الحل" | "نقاش مفتوح" | "مقال" | "فرصة" | "بحاجة لإجابة";
  tags: string[];
  score: number;
  replies: number;
  views: string;
  authorName: string;
  authorHandle: string;
  avatarUrl?: string;
  createdAtLabel: string;
  lastActivityLabel: string;
};

const avatar = (seed: string) =>
  `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(seed)}`;

export const FORUM_GROUPS: ForumGroup[] = [
  {
    id: "programming",
    title: "البرمجة وتطوير الويب",
    description: "كل ما يخص لغات البرمجة، الويب، والأدوات الحديثة.",
    forums: [
      {
        id: "js-ts",
        title: "JavaScript / TypeScript",
        description: "نقاشات عن JS الحديثة، TypeScript، وأنماط الكتابة النظيفة.",
        href: "/questions?tag=JavaScript",
        icon: "Code2",
        viewers: 87,
        topicsCount: "2.1K",
        postsCount: "14.3K",
        isNew: true,
        category: "programming",
        tags: ["JavaScript", "TypeScript", "Node"],
        latest: {
          title: "أفضل طريقة لاستخدام Generics في TypeScript؟",
          type: "سؤال",
          authorName: "سامي",
          authorHandle: "@sami_codes",
          avatarUrl: avatar("sami"),
          relativeTime: "منذ 12 دقيقة",
          exactTime: "اليوم في 14:20",
        },
      },
      {
        id: "react-ui",
        title: "React وواجهات المستخدم",
        description: "نقاشات ومشاكل وحلول حول React, UI, Tailwind, shadcn, performance.",
        href: "/questions?tag=React",
        icon: "Atom",
        viewers: 42,
        topicsCount: "1.2K",
        postsCount: "8.4K",
        isNew: true,
        category: "programming",
        tags: ["React", "Tailwind", "UI"],
        latest: {
          title: "أفضل طريقة لتنظيم components في مشروع كبير؟",
          type: "سؤال",
          authorName: "أحمد",
          authorHandle: "@ahmad_dev",
          avatarUrl: avatar("ahmad"),
          relativeTime: "منذ 24 دقيقة",
          exactTime: "اليوم في 13:58",
        },
      },
      {
        id: "backend",
        title: "Backend و APIs",
        description: "بناء APIs موثوقة، أنماط REST/GraphQL، وأمان الخادم.",
        href: "/questions?tag=Backend",
        icon: "Server",
        viewers: 31,
        topicsCount: "980",
        postsCount: "5.6K",
        isNew: false,
        category: "programming",
        tags: ["Node", "API", "REST"],
        latest: {
          title: "كيف أحمي API من هجمات الـ brute force؟",
          type: "نقاش",
          authorName: "ليث",
          authorHandle: "@laith_be",
          avatarUrl: avatar("laith"),
          relativeTime: "منذ 50 دقيقة",
          exactTime: "اليوم في 13:32",
        },
      },
      {
        id: "db",
        title: "قواعد البيانات و Supabase",
        description: "SQL، Postgres، RLS، والاستعلامات المتقدمة.",
        href: "/questions?tag=Supabase",
        icon: "Database",
        viewers: 25,
        topicsCount: "640",
        postsCount: "3.9K",
        isNew: false,
        category: "programming",
        tags: ["Supabase", "Postgres", "SQL"],
        latest: {
          title: "كتابة RLS آمن للجدول العام",
          type: "مقال",
          authorName: "منى",
          authorHandle: "@mona_data",
          avatarUrl: avatar("mona"),
          relativeTime: "منذ ساعة",
          exactTime: "اليوم في 13:05",
        },
      },
      {
        id: "devops",
        title: "DevOps و Docker",
        description: "CI/CD، حاويات، والنشر على السحابة.",
        href: "/questions?tag=DevOps",
        icon: "Container",
        viewers: 18,
        topicsCount: "420",
        postsCount: "2.1K",
        isNew: false,
        category: "programming",
        tags: ["Docker", "CI/CD", "AWS"],
        latest: {
          title: "خطوات نشر مشروع Vite على VPS بـ Nginx",
          type: "مقال",
          authorName: "ياسر",
          authorHandle: "@yaser_ops",
          avatarUrl: avatar("yaser"),
          relativeTime: "منذ ساعتين",
          exactTime: "اليوم في 12:04",
        },
      },
      {
        id: "wp-cms",
        title: "WordPress و CMS",
        description: "قوالب، إضافات، وأداء مواقع ووردبريس.",
        href: "/questions?tag=WordPress",
        icon: "Layout",
        viewers: 12,
        topicsCount: "310",
        postsCount: "1.4K",
        isNew: false,
        category: "programming",
        tags: ["WordPress", "PHP", "SEO"],
        latest: {
          title: "أفضل إضافة كاش لموقع بحمل عالي؟",
          type: "سؤال",
          authorName: "خالد",
          authorHandle: "@khaled_wp",
          avatarUrl: avatar("khaled"),
          relativeTime: "منذ 3 ساعات",
          exactTime: "اليوم في 11:12",
        },
      },
    ],
  },
  {
    id: "ai",
    title: "الذكاء الاصطناعي والبيانات",
    description: "أدوات AI، هندسة البرومبت، وبناء منتجات ذكية.",
    forums: [
      {
        id: "ai-tools",
        title: "أدوات الذكاء الاصطناعي",
        description: "أفضل الأدوات لتسريع عملك اليومي.",
        href: "/articles?tag=AI",
        icon: "Sparkles",
        viewers: 64,
        topicsCount: "540",
        postsCount: "3.2K",
        isNew: true,
        category: "ai",
        tags: ["AI", "Tools", "Productivity"],
        latest: {
          title: "قائمة أدوات AI ضرورية لكل مبرمج في 2026",
          type: "مقال",
          authorName: "سارة",
          authorHandle: "@sara_ai",
          avatarUrl: avatar("sara"),
          relativeTime: "منذ 20 دقيقة",
          exactTime: "اليوم في 14:10",
        },
      },
      {
        id: "prompt",
        title: "Prompt Engineering",
        description: "أنماط البرومبت الفعّالة والنتائج القابلة للتكرار.",
        href: "/articles?tag=Prompt",
        icon: "MessagesSquare",
        viewers: 33,
        topicsCount: "280",
        postsCount: "1.6K",
        isNew: true,
        category: "ai",
        tags: ["Prompt", "LLM"],
        latest: {
          title: "قوالب برومبت لبناء منتجات SaaS",
          type: "نقاش",
          authorName: "رهف",
          authorHandle: "@rahaf_p",
          avatarUrl: avatar("rahaf"),
          relativeTime: "منذ 40 دقيقة",
          exactTime: "اليوم في 13:50",
        },
      },
      {
        id: "data",
        title: "Data Analysis",
        description: "تحليل البيانات، Pandas، وتصور النتائج.",
        href: "/articles?tag=Data",
        icon: "LineChart",
        viewers: 19,
        topicsCount: "190",
        postsCount: "980",
        isNew: false,
        category: "ai",
        tags: ["Python", "Pandas", "Data"],
        latest: {
          title: "من CSV إلى Dashboard خلال ساعة",
          type: "مقال",
          authorName: "طارق",
          authorHandle: "@tariq_da",
          avatarUrl: avatar("tariq"),
          relativeTime: "منذ ساعتين",
          exactTime: "اليوم في 12:22",
        },
      },
      {
        id: "automation",
        title: "Automation",
        description: "أتمتة المهام المتكررة و n8n و Zapier.",
        href: "/articles?tag=Automation",
        icon: "Workflow",
        viewers: 15,
        topicsCount: "150",
        postsCount: "720",
        isNew: false,
        category: "ai",
        tags: ["n8n", "Zapier", "Automation"],
        latest: {
          title: "أتمتة رد العملاء عبر واتساب",
          type: "نقاش",
          authorName: "بلال",
          authorHandle: "@bilal_auto",
          avatarUrl: avatar("bilal"),
          relativeTime: "منذ 5 ساعات",
          exactTime: "اليوم في 09:30",
        },
      },
      {
        id: "ai-products",
        title: "بناء منتجات AI",
        description: "من الفكرة إلى SaaS مدعوم بذكاء اصطناعي.",
        href: "/articles?tag=AI-Product",
        icon: "Rocket",
        viewers: 27,
        topicsCount: "210",
        postsCount: "1.1K",
        isNew: true,
        category: "ai",
        tags: ["SaaS", "AI", "Startup"],
        latest: {
          title: "كيف أطلقت منتجي الأول خلال 3 أسابيع",
          type: "مقال",
          authorName: "ندى",
          authorHandle: "@nada_build",
          avatarUrl: avatar("nada"),
          relativeTime: "الأمس",
          exactTime: "الأمس في 23:55",
        },
      },
    ],
  },
  {
    id: "freelancing",
    title: "عالم الفريلانس",
    description: "التسعير، العملاء، والعقود.",
    forums: [
      {
        id: "pricing",
        title: "التسعير والعروض",
        description: "كيف تسعّر عملك وترسل عروض مقنعة.",
        href: "/articles?tag=Pricing",
        icon: "DollarSign",
        viewers: 44,
        topicsCount: "310",
        postsCount: "2.4K",
        isNew: true,
        category: "freelancing",
        tags: ["Pricing", "Freelance"],
        latest: {
          title: "متى ترفع أسعارك كمستقل؟",
          type: "نقاش",
          authorName: "علي",
          authorHandle: "@ali_freelance",
          avatarUrl: avatar("ali"),
          relativeTime: "منذ 30 دقيقة",
          exactTime: "اليوم في 14:00",
        },
      },
      {
        id: "clients",
        title: "التعامل مع العملاء",
        description: "التواصل، الحدود، وحل النزاعات.",
        href: "/articles?tag=Clients",
        icon: "Users",
        viewers: 28,
        topicsCount: "220",
        postsCount: "1.5K",
        isNew: false,
        category: "freelancing",
        tags: ["Clients", "Soft Skills"],
        latest: {
          title: "كيف أرفض مشروع بأدب؟",
          type: "سؤال",
          authorName: "روان",
          authorHandle: "@rawan_fl",
          avatarUrl: avatar("rawan"),
          relativeTime: "منذ ساعة",
          exactTime: "اليوم في 13:20",
        },
      },
      {
        id: "platforms",
        title: "منصات العمل الحر",
        description: "Upwork، Freelancer، مستقل، خمسات، وغيرها.",
        href: "/articles?tag=Platforms",
        icon: "Globe",
        viewers: 22,
        topicsCount: "180",
        postsCount: "1.1K",
        isNew: false,
        category: "freelancing",
        tags: ["Upwork", "Mostaql"],
        latest: {
          title: "أول عرض ناجح لي على Upwork",
          type: "مقال",
          authorName: "حسام",
          authorHandle: "@hussam_up",
          avatarUrl: avatar("hussam"),
          relativeTime: "منذ 4 ساعات",
          exactTime: "اليوم في 10:15",
        },
      },
      {
        id: "contracts",
        title: "العقود والدفع",
        description: "قوالب عقود، طرق دفع، وحماية حقوقك.",
        href: "/articles?tag=Contracts",
        icon: "FileText",
        viewers: 17,
        topicsCount: "120",
        postsCount: "780",
        isNew: false,
        category: "freelancing",
        tags: ["Contracts", "Payment"],
        latest: {
          title: "أفضل طرق استلام الدفع في فلسطين",
          type: "سؤال",
          authorName: "دانا",
          authorHandle: "@dana_pay",
          avatarUrl: avatar("dana"),
          relativeTime: "الأمس",
          exactTime: "الأمس في 22:10",
        },
      },
      {
        id: "portfolio",
        title: "بناء البورتفوليو",
        description: "اعرض عملك بطريقة تلفت العميل.",
        href: "/articles?tag=Portfolio",
        icon: "Briefcase",
        viewers: 20,
        topicsCount: "160",
        postsCount: "920",
        isNew: true,
        category: "freelancing",
        tags: ["Portfolio", "Branding"],
        latest: {
          title: "قوالب بورتفوليو مبرمج فرونت اند",
          type: "مقال",
          authorName: "ليان",
          authorHandle: "@layan_ux",
          avatarUrl: avatar("layan"),
          relativeTime: "منذ 6 ساعات",
          exactTime: "اليوم في 08:44",
        },
      },
    ],
  },
  {
    id: "career",
    title: "المسار المهني",
    description: "السيرة، المقابلات، والفرص المهنية.",
    forums: [
      {
        id: "cv",
        title: "CV و LinkedIn",
        description: "تحسين ملفك المهني وجذب المسؤولين.",
        href: "/articles?tag=CV",
        icon: "IdCard",
        viewers: 29,
        topicsCount: "240",
        postsCount: "1.3K",
        isNew: false,
        category: "career",
        tags: ["CV", "LinkedIn"],
        latest: {
          title: "كلمات مفتاحية تجذب Recruiters",
          type: "مقال",
          authorName: "عمر",
          authorHandle: "@omar_hr",
          avatarUrl: avatar("omar"),
          relativeTime: "منذ ساعة",
          exactTime: "اليوم في 13:10",
        },
      },
      {
        id: "interviews",
        title: "مقابلات تقنية",
        description: "أسئلة شائعة، Data Structures، و System Design.",
        href: "/questions?tag=Interviews",
        icon: "MessageCircle",
        viewers: 35,
        topicsCount: "410",
        postsCount: "2.6K",
        isNew: true,
        category: "career",
        tags: ["Interview", "DSA"],
        latest: {
          title: "سؤال System Design لشركة كبرى",
          type: "سؤال",
          authorName: "زين",
          authorHandle: "@zain_dsa",
          avatarUrl: avatar("zain"),
          relativeTime: "منذ 45 دقيقة",
          exactTime: "اليوم في 13:35",
        },
      },
      {
        id: "internships",
        title: "فرص تدريب",
        description: "تدريبات مدفوعة ومجانية للمبرمجين.",
        href: "/jobs?type=internship",
        icon: "GraduationCap",
        viewers: 21,
        topicsCount: "160",
        postsCount: "820",
        isNew: false,
        category: "career",
        tags: ["Internship", "Training"],
        latest: {
          title: "تدريب صيفي عن بعد لشركة أوروبية",
          type: "فرصة",
          authorName: "هبة",
          authorHandle: "@heba_jobs",
          avatarUrl: avatar("heba"),
          relativeTime: "منذ ساعتين",
          exactTime: "اليوم في 12:00",
        },
      },
      {
        id: "remote",
        title: "Remote Jobs",
        description: "وظائف عن بعد للمبرمجين العرب.",
        href: "/jobs?type=remote",
        icon: "MonitorSmartphone",
        viewers: 47,
        topicsCount: "380",
        postsCount: "2.2K",
        isNew: true,
        category: "career",
        tags: ["Remote", "Jobs"],
        latest: {
          title: "وظيفة React Senior — راتب دولار",
          type: "فرصة",
          authorName: "فادي",
          authorHandle: "@fadi_remote",
          avatarUrl: avatar("fadi"),
          relativeTime: "منذ 15 دقيقة",
          exactTime: "اليوم في 14:05",
        },
      },
      {
        id: "stories",
        title: "قصص وتجارب مهنية",
        description: "تجارب حقيقية من مبرمجين عرب.",
        href: "/articles?tag=Stories",
        icon: "BookOpen",
        viewers: 14,
        topicsCount: "110",
        postsCount: "540",
        isNew: false,
        category: "career",
        tags: ["Stories"],
        latest: {
          title: "من مبرمج مبتدئ إلى Tech Lead خلال 4 سنوات",
          type: "مقال",
          authorName: "لينا",
          authorHandle: "@lina_lead",
          avatarUrl: avatar("lina"),
          relativeTime: "الأمس",
          exactTime: "الأمس في 20:30",
        },
      },
    ],
  },
  {
    id: "library",
    title: "مكتبة WekiCode",
    description: "مقالات، كورسات، Roadmaps ومصادر مختارة.",
    forums: [
      {
        id: "tech-articles",
        title: "مقالات تقنية",
        description: "مقالات معمقة من مجتمع WekiCode.",
        href: "/articles",
        icon: "FileText",
        viewers: 38,
        topicsCount: "1.4K",
        postsCount: "6.8K",
        isNew: true,
        category: "library",
        tags: ["Articles"],
        latest: {
          title: "شرح مفصل لـ React Server Components",
          type: "مقال",
          authorName: "أنس",
          authorHandle: "@anas_rsc",
          avatarUrl: avatar("anas"),
          relativeTime: "منذ 25 دقيقة",
          exactTime: "اليوم في 13:55",
        },
      },
      {
        id: "courses",
        title: "كورسات ومسارات",
        description: "كورسات عملية بمسارات واضحة.",
        href: "/courses",
        icon: "GraduationCap",
        viewers: 52,
        topicsCount: "220",
        postsCount: "3.4K",
        isNew: true,
        category: "library",
        tags: ["Courses", "Learning"],
        latest: {
          title: "كورس React من الصفر إلى المشاريع الحقيقية",
          type: "مقال",
          authorName: "منصور",
          authorHandle: "@mansour_edu",
          avatarUrl: avatar("mansour"),
          relativeTime: "منذ 10 دقائق",
          exactTime: "اليوم في 14:15",
        },
      },
      {
        id: "roadmaps",
        title: "Roadmaps",
        description: "خرائط طريق لكل تخصص برمجي.",
        href: "/articles?tag=Roadmap",
        icon: "Map",
        viewers: 33,
        topicsCount: "80",
        postsCount: "610",
        isNew: false,
        category: "library",
        tags: ["Roadmap"],
        latest: {
          title: "خارطة طريق Backend Developer 2026",
          type: "مقال",
          authorName: "ريم",
          authorHandle: "@reem_map",
          avatarUrl: avatar("reem"),
          relativeTime: "منذ 3 ساعات",
          exactTime: "اليوم في 11:20",
        },
      },
      {
        id: "tools",
        title: "أدوات ومصادر",
        description: "قوائم أدوات لكل مرحلة.",
        href: "/articles?tag=Tools",
        icon: "Wrench",
        viewers: 24,
        topicsCount: "140",
        postsCount: "890",
        isNew: false,
        category: "library",
        tags: ["Tools"],
        latest: {
          title: "أدوات تصميم لواجهات سريعة",
          type: "مقال",
          authorName: "سلمى",
          authorHandle: "@salma_ui",
          avatarUrl: avatar("salma"),
          relativeTime: "الأمس",
          exactTime: "الأمس في 21:00",
        },
      },
      {
        id: "projects",
        title: "مشاريع قابلة للتطبيق",
        description: "أفكار مشاريع للتدرب وبناء البورتفوليو.",
        href: "/articles?tag=Projects",
        icon: "Boxes",
        viewers: 30,
        topicsCount: "170",
        postsCount: "1.0K",
        isNew: true,
        category: "library",
        tags: ["Projects"],
        latest: {
          title: "10 مشاريع Full-Stack لبورتفوليو قوي",
          type: "مقال",
          authorName: "كريم",
          authorHandle: "@karim_proj",
          avatarUrl: avatar("karim"),
          relativeTime: "منذ ساعتين",
          exactTime: "اليوم في 12:30",
        },
      },
    ],
  },
  {
    id: "community",
    title: "المجتمع",
    description: "نقاشات عامة، مشاريع الأعضاء، وإعلانات المنصة.",
    forums: [
      {
        id: "general",
        title: "نقاشات عامة",
        description: "أي شيء يهم المبرمج والمستقل العربي.",
        href: "/questions?tag=General",
        icon: "Hash",
        viewers: 41,
        topicsCount: "620",
        postsCount: "4.1K",
        isNew: false,
        category: "community",
        tags: ["General"],
        latest: {
          title: "أفضل ساعات إنتاجية بالنسبة لك؟",
          type: "نقاش",
          authorName: "يزن",
          authorHandle: "@yazan_talk",
          avatarUrl: avatar("yazan"),
          relativeTime: "منذ 8 دقائق",
          exactTime: "اليوم في 14:17",
        },
      },
      {
        id: "showcase",
        title: "اعرض مشروعك",
        description: "شارك مشروعك واحصل على تعليقات.",
        href: "/developers",
        icon: "Presentation",
        viewers: 26,
        topicsCount: "310",
        postsCount: "1.8K",
        isNew: true,
        category: "community",
        tags: ["Showcase"],
        latest: {
          title: "أطلقت أول SaaS، رأيكم؟",
          type: "نقاش",
          authorName: "مؤيد",
          authorHandle: "@moaid_saas",
          avatarUrl: avatar("moaid"),
          relativeTime: "منذ 35 دقيقة",
          exactTime: "اليوم في 13:45",
        },
      },
      {
        id: "achievements",
        title: "إنجازات الأعضاء",
        description: "احتفل بإنجازك مع المجتمع.",
        href: "/leaderboard",
        icon: "Trophy",
        viewers: 19,
        topicsCount: "150",
        postsCount: "740",
        isNew: false,
        category: "community",
        tags: ["Achievements"],
        latest: {
          title: "حصلت على أول عميل من WekiCode",
          type: "نقاش",
          authorName: "شهد",
          authorHandle: "@shahd_win",
          avatarUrl: avatar("shahd"),
          relativeTime: "منذ 55 دقيقة",
          exactTime: "اليوم في 13:25",
        },
      },
      {
        id: "announcements",
        title: "إعلانات المنصة",
        description: "تحديثات وميزات WekiCode الجديدة.",
        href: "/",
        icon: "Megaphone",
        viewers: 58,
        topicsCount: "60",
        postsCount: "310",
        isNew: true,
        category: "community",
        tags: ["Announcements"],
        latest: {
          title: "أطلقنا مسارات تعلم جديدة",
          type: "مقال",
          authorName: "فريق WekiCode",
          authorHandle: "@wekicode",
          avatarUrl: avatar("wekicode"),
          relativeTime: "اليوم",
          exactTime: "اليوم في 09:00",
        },
      },
      {
        id: "suggestions",
        title: "اقتراحات وتطوير WekiCode",
        description: "شارك اقتراحاتك لتطوير المنصة.",
        href: "/",
        icon: "Lightbulb",
        viewers: 17,
        topicsCount: "90",
        postsCount: "420",
        isNew: false,
        category: "community",
        tags: ["Feedback"],
        latest: {
          title: "اقتراح: إضافة نظام سمعة مرئي",
          type: "نقاش",
          authorName: "براء",
          authorHandle: "@baraa_ideas",
          avatarUrl: avatar("baraa"),
          relativeTime: "الأمس",
          exactTime: "الأمس في 19:45",
        },
      },
    ],
  },
];

export const DISCUSSIONS: DiscussionItem[] = [
  {
    id: "d1",
    title: "أفضل طريقة لتنظيم components في مشروع React كبير؟",
    excerpt: "أعمل على مشروع فيه أكثر من 200 كومبوننت وأبحث عن نمط تنظيمي واضح…",
    href: "/questions",
    category: "برمجة",
    status: "نقاش مفتوح",
    tags: ["React", "Architecture", "Tailwind"],
    score: 42,
    replies: 18,
    views: "1.2K",
    authorName: "أحمد",
    authorHandle: "@ahmad_dev",
    avatarUrl: avatar("ahmad"),
    createdAtLabel: "اليوم في 09:15",
    lastActivityLabel: "منذ 12 دقيقة",
  },
  {
    id: "d2",
    title: "كيف أسعّر مشروع متجر إلكتروني كامل؟",
    excerpt: "عميل يطلب متجر مع لوحة تحكم ودفع إلكتروني، ما السعر المناسب؟",
    href: "/articles",
    category: "فريلانس",
    status: "بحاجة لإجابة",
    tags: ["Pricing", "Freelance"],
    score: 28,
    replies: 9,
    views: "640",
    authorName: "روان",
    authorHandle: "@rawan_fl",
    avatarUrl: avatar("rawan"),
    createdAtLabel: "اليوم في 10:30",
    lastActivityLabel: "منذ 25 دقيقة",
  },
  {
    id: "d3",
    title: "قائمة أدوات AI ضرورية لكل مبرمج في 2026",
    excerpt: "جمعت أهم 20 أداة استخدمها يوميًا في العمل والبرمجة…",
    href: "/articles",
    category: "ذكاء اصطناعي",
    status: "مقال",
    tags: ["AI", "Tools"],
    score: 96,
    replies: 34,
    views: "3.4K",
    authorName: "سارة",
    authorHandle: "@sara_ai",
    avatarUrl: avatar("sara"),
    createdAtLabel: "الأمس في 22:10",
    lastActivityLabel: "منذ 20 دقيقة",
  },
  {
    id: "d4",
    title: "وظيفة React Senior — راتب دولار عن بعد",
    excerpt: "شركة أوروبية تبحث عن مطور React خبرة 3+ سنوات…",
    href: "/jobs",
    category: "وظائف",
    status: "فرصة",
    tags: ["Remote", "React", "Jobs"],
    score: 51,
    replies: 12,
    views: "980",
    authorName: "فادي",
    authorHandle: "@fadi_remote",
    avatarUrl: avatar("fadi"),
    createdAtLabel: "اليوم في 08:00",
    lastActivityLabel: "منذ 15 دقيقة",
  },
  {
    id: "d5",
    title: "كيف أحمي API من هجمات brute force؟",
    excerpt: "أستخدم Node/Express وأبحث عن أفضل ممارسات الحماية…",
    href: "/questions",
    category: "برمجة",
    status: "تم الحل",
    tags: ["Backend", "Security", "API"],
    score: 37,
    replies: 15,
    views: "820",
    authorName: "ليث",
    authorHandle: "@laith_be",
    avatarUrl: avatar("laith"),
    createdAtLabel: "الأمس في 18:40",
    lastActivityLabel: "منذ 50 دقيقة",
  },
  {
    id: "d6",
    title: "أطلقت أول SaaS بذكاء اصطناعي — تجربتي الكاملة",
    excerpt: "من الفكرة إلى أول عميل خلال 21 يوم، هذه التفاصيل…",
    href: "/articles",
    category: "مقالات",
    status: "مقال",
    tags: ["SaaS", "AI", "Startup"],
    score: 74,
    replies: 22,
    views: "2.1K",
    authorName: "ندى",
    authorHandle: "@nada_build",
    avatarUrl: avatar("nada"),
    createdAtLabel: "الأمس في 23:55",
    lastActivityLabel: "منذ ساعة",
  },
  {
    id: "d7",
    title: "متى ترفع أسعارك كمستقل؟",
    excerpt: "نقاش مفتوح، شاركونا معايير رفع الأسعار عندكم…",
    href: "/articles",
    category: "فريلانس",
    status: "نقاش مفتوح",
    tags: ["Pricing", "Freelance"],
    score: 33,
    replies: 27,
    views: "1.1K",
    authorName: "علي",
    authorHandle: "@ali_freelance",
    avatarUrl: avatar("ali"),
    createdAtLabel: "اليوم في 11:00",
    lastActivityLabel: "منذ 30 دقيقة",
  },
  {
    id: "d8",
    title: "خارطة طريق Backend Developer 2026",
    excerpt: "المهارات والأدوات الأساسية بترتيب منطقي…",
    href: "/articles",
    category: "مقالات",
    status: "مقال",
    tags: ["Roadmap", "Backend"],
    score: 58,
    replies: 11,
    views: "1.6K",
    authorName: "ريم",
    authorHandle: "@reem_map",
    avatarUrl: avatar("reem"),
    createdAtLabel: "أمس في 15:30",
    lastActivityLabel: "منذ 3 ساعات",
  },
];

export const TRENDING_TAGS = [
  "React", "JavaScript", "TypeScript", "Python", "Supabase",
  "Freelancing", "Pricing", "Portfolio", "AI", "WordPress", "Docker", "Remote Work",
];

export const LEARNING_PATHS = [
  { title: "Frontend Developer", desc: "HTML/CSS/JS/React", progress: 62, href: "/courses" },
  { title: "Backend Developer", desc: "Node, APIs, Databases", progress: 45, href: "/courses" },
  { title: "Freelancer Starter", desc: "من الصفر إلى أول عميل", progress: 30, href: "/articles?tag=Freelance" },
  { title: "AI Tools for Developers", desc: "أدوات AI للإنتاجية", progress: 20, href: "/articles?tag=AI" },
  { title: "Portfolio Builder", desc: "بورتفوليو يجذب العملاء", progress: 55, href: "/articles?tag=Portfolio" },
];

export const TOP_CONTRIBUTORS = [
  { name: "سارة", handle: "@sara_ai", points: 12840, specialty: "AI & Prompting", avatarUrl: avatar("sara") },
  { name: "أحمد", handle: "@ahmad_dev", points: 9420, specialty: "React & UI", avatarUrl: avatar("ahmad") },
  { name: "ندى", handle: "@nada_build", points: 8710, specialty: "SaaS & Product", avatarUrl: avatar("nada") },
  { name: "فادي", handle: "@fadi_remote", points: 7650, specialty: "Remote Careers", avatarUrl: avatar("fadi") },
];

export const COMMUNITY_STATS = [
  { label: "عضو", value: "12.8K" },
  { label: "موضوع", value: "4.6K" },
  { label: "مشاركة", value: "38.2K" },
  { label: "حل موثّق", value: "890" },
];